### ISSUE TITLE
es6 support

### ISSUE THREAD

**Issue by btamas** [lasso-js/lasso-require#13]
Hi,

I have an ES6 file, that I want to bundle with lasso and lasso-require.
I cannot found in the documentation, but I saw that is supported, if I rename my file to .es6.

During the build the lasso was missing the babel-runtime plugin. I installed it, and the build was success. But when I opened it in a browser, I got the following error: 
Uncaught Error: Cannot find module "/$/babel-runtime/$/core-js/library/modules/$" from "/$/babel-runtime/$/core-js/library/fn/object"

I tried to understand what can be the problem, but I cannot found. I have some idea, but it is only an idea. Can it make problem, that the babel-runtime has a lot of files with names that contains $ (dollar sign)? Like $.js

I tried to make a workaround and I used the es6ify browserify transform with lasso-require. It worked properly, but when I want to use it for tests (mocha, sinon), I got the error message because I cannot access to caller, callee, etc in strict mode. This happend because the sinon.spy want so access to this attributes, but in strict mode it is not allowed. I would like to disable strict mode, but I cannot know how can I give config parameters to a transform in lasso-require config. If I opened the bundle and remove all "use strict"; lines, it worked propertly. So, can I give config options to a transform in lasso-require config?

Thanks in advance.

**Comment by patrick-steele-idem** [comment]
Thanks for the details @btamas! I'll investigate based on your feedback to make sure there are no issues and put in any fixes if needed. I'll get back to you soon.

**Comment by patrick-steele-idem** [comment]
Damn... who uses `$` in filenames? That is definitely breaking things. Working on a fix now. Thanks for opening the issue.

**Comment by patrick-steele-idem** [comment]
New version of `lasso-require` published with a fix to better handle JavaScript modules that use `$` in the filename (a special character for the client-side Lasso.js module runtime). New version: `lasso-require@1.3.9`

You should be able to get things working by not using `es6ify` and using the `.es6` extension. Let me know if you still have issues. I'm going to do additional testing as well. Thanks again.

**Comment by btamas** [comment]
It was fast, but unfortunately it isn't working for me.
I put some console log to the function that you modified, but it has never called.

I created a gist, that contains my code, so you can try it. Maybe I screwed something.
https://gist.github.com/btamas/b657b9fccedfa9a4104e

**Comment by patrick-steele-idem** [comment]
Great. It's still a work-in-progress, but I've also added a sample app that you might find helpful: https://github.com/lasso-js-samples/lasso-es6

Let us know if you run into any other issues! Thanks again for let us know if the issue. Glad the problem has been resolved for you.
