### ISSUE TITLE
lasso-require > 1.3.7 failing for marko-widgets in Windows environment

### ISSUE THREAD

**Issue by pranavjha** [lasso-js/lasso-require#14]
the marko template requires are getting translated with dependency paths having `\` instead of `/` in windows. This issue comes only on version 1.3.8 and above

**Comment by patrick-steele-idem** [comment]
I'm not seeing any related changes to path handling.  Can you provide more details?

**Comment by philidem** [comment]
Is this still an issue?

**Comment by pranavjha** [comment]
will check and reopen if necessary.
