### ISSUE TITLE
Doesn't support Babel 6.0.0, the [preset] option will fail the transformation.

### ISSUE THREAD

**Issue by leonli** [lasso-js/lasso-require#15]
Error: Async fragment failed (lasso-slot:body). Exception: ReferenceError: [BABEL] /Users/leonli/GitHub/lkm-starter/src/views/client/something.es6: Unknown option: /Users/leonli/GitHub/lkm-starter/.babelrc.presets

**Comment by leonli** [comment]
@patrick-steele-idem have you considered to upgrade Babel to 6.0.x?

**Comment by patrick-steele-idem** [comment]
Hey @leonli, I'm surprised we are not using `babel@^6`. Would you be interested in upgrading this module to use the latest version of babel? Thanks in advance!

**Comment by leonli** [comment]
Sure, I'd like to send a PR to this module, but since babel 6.x is much different than the 5.x, the options and the plugin system have changed their APIs, so they won't be compatibility. Will you accept a PR for the incompatible upgrade?

**Comment by patrick-steele-idem** [comment]
Yes, I will accept a PR with incompatible changes because I think it is more important that we use the latest version of babel. Based on the PR we can decide if we need to upgrade the major version, but in theory existing ES6 code that is transpiled should continue to work with no issues.

**Comment by leonli** [comment]
I almost done the PR. But before I'm sending it to this module, I'd like to share an interesting performance issue here.

According to the test cases I was running in `Lasso` project, the `babel 6.x` is about 5 times slower than the `babel 5.x`, it completely doesn't make sense as the babel official team has posted in their blog that they have improved the performance in `babel 6.x` (increased about 20%). But the test case running in `Lasso` didn't show the correct result, as I mentioned about, `6.x` is about 5 times slower, after then I did some research to improve the performance when using `babel 6.x`, the original post is [here](https://github.com/babel/babel/issues/2706), according to the post, I upgraded my node environment from `node 4.2.1, npm 2.14.7` to `node 4.2.1, npm 3.3.10`, after reinstalling the `babel 6.x` library, the performance got improved pretty much(Screenshots attached below). 

`npm v2.14.7`
![screen shot 2015-11-04 at 1 49 30 pm](https://cloud.githubusercontent.com/assets/345188/10930901/bc8f3094-82fd-11e5-9965-125efcd104e3.png)

`npm v3.3.10`
![screen shot 2015-11-04 at 1 53 27 pm](https://cloud.githubusercontent.com/assets/345188/10930892/9e1c95e8-82fd-11e5-85c8-5fbfce6ae42d.png)

Conclusion:
1). Before I'm sending the upgrading PR for this module, I'd like to inform that the `babel 6.x` so far is just performing better performance when it's running on `npm 3.3.x`.
2). I'm finishing my tests soon, and a few APIs would be changed in this module and `Lasso.js` project, I think the new option changes would affect the users who are using `Lasso.js` with `babel 5.x`, this does matter to upgrade user's configuration once the PR is getting accepted.

**Comment by leonli** [comment]
@patrick-steele-idem how's it going?

**Comment by patrick-steele-idem** [comment]
Hey @leonli, still here! Sorry. I did not have a chance to review your comments today. Any idea why npm version impacts runtime performance of babel? That seems very strange!  Thank you for working on this PR.

**Comment by leonli** [comment]
@patrick-steele-idem According to the author of Babel, he said it's because they change the way that how Babel compile the code, I didn't walk into the detail, instead of that, I'd post my test here for anyone who would find out that the performance is getting slower than the previous version of Babel, that the `npm node-gyp` build would be the cause.
