### ISSUE TITLE
getDependencies() in dep-require.js doesn't always return all of the dependencies

### ISSUE THREAD

**Issue by philidem** [lasso-js/lasso-require#33]
It looks like there are a couple of return paths that don't return all of the dependencies that have been collected thus far.

This was the problem return path that affected my project:
```javascript
if (!requireHandler) {
    // This is not really a dependency that compiles down to a CommonJS module
    // so just add it to the dependency graph
    return [resolved.path];
}
```

The fix is to add `resolved.path` to the list of `dependencies` and then return `dependencies` (instead of returning a new array). If you return `[resolved.path]` then there is a chance that the automatically added `commonjs-ready` and `commonjs-runtime` dependencies will not be returned.

A couple of other short-circuit return paths seem to have the same problem. I have a fix ready.

**Comment by patrick-steele-idem** [comment]
A fix has been published with `lasso-require@2.2.3`. Closing issue.
